### ISSUE TITLE
Evaluation problem

### ISSUE THREAD

**Issue by ZhangShiyue** [google/seq2seq#98] opened 2017-03-22 07:48 UTC
Hi, 

I'm trying to train NMT model on WMT'16 en-de data, as shown in Tutorial. I have trained successfully on toydata. But I got an evaluation problem on en-de data.  It seems it can train, but when it is time to do evaluation, it will be failed. Error info is shown below:

INFO:tensorflow:Starting evaluation at 2017-03-22-07:29:57
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
W tensorflow/core/framework/op_kernel.cc:993] Out of range: Reached limit of 1
         [[Node: parallel_read/filenames/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@parallel_read/filenames/limit_epochs/epochs"], limit=1, _device="/job:localhost/replica:0/task:0/cpu:0"](parallel_read/filenames/limit_epochs/epochs)]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Tried to read from index 49 but array size is: 49
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Tried to read from index 49 but array size is: 49
         [[Node: model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3 = TensorArrayReadV3[_class=["loc:@model/att_seq2seq/decode/TrainingHelper/TensorArray"], dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch, model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch_1/_419, model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch_2)]]
W tensorflow/core/framework/op_kernel.cc:993] Invalid argument: Tried to read from index 49 but array size is: 49
         [[Node: model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3 = TensorArrayReadV3[_class=["loc:@model/att_seq2seq/decode/TrainingHelper/TensorArray"], dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch, model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch_1/_419, model/att_seq2seq/decode/attention_decoder_1/decoder/while/CustomHelperNextInputs/TrainingHelperNextInputs/cond/TensorArrayReadV3/Switch_2)]]

It is very strange that I didn't encounter this problem on toy data. And I did't change any configuration. 
I use the default 'nmt_small.yml'. 

I really need help. Is there anyone who knows how to fix it? Thanks a lot!

**Comment by dennybritz** [comment] 2017-03-22 16:03
Duplicate of #69

**Closed by dennybritz** 2017-03-22 16:03 UTC
